#!/usr/bin/env ts-node

/**
 * Script to ingest actual messages from channel C08T43UHK9D
 * Uses the messages fetched from Slack MCP
 */

import * as dotenv from 'dotenv';
dotenv.config();

import { ingestSignal, RawSignal } from '../backend/processing/signal_extractor';
import { logger } from '../backend/utils/logger';

// Messages fetched from Slack channel C08T43UHK9D
const messages = [
  {
    ts: '1747994441.524969',
    text: '*<https://www.clarkcountynv.gov/|Clark County> Went live on Friday (16th May) !* :partying_face:\n\n• Clark County is the first forms customer to go-live on *forms-x-walk using Universal Editor*!\n• 24 forms went live delivering seem less form filling experience across the county site.\n• The VIP team used Experience Builder to create most of the content and rules. Authoring was completed in ~2 days.\n• All forms were configured to Power-Automate submission that triggered an email to the respective county department mailboxes.\nA huge shoutout to the VIP team: <@W4V7BFNKD> <@W4R4PH17S> <@W4ZA9ATAM>\nAnd thanks to forms engg team: <@U01G51VDXB8> <@U03QB0GK45Q> <@U06NF880220> <@U03N27GAZDZ> <@WLWHN4TV3> <@W6CBB4953> <@W6CBB6337> <@U04P75X4H1B>\n\nCongrats to everyone involved in making this a successful golive! :tada:\n\ncc: <@W4RU4N66R> <@W4RSW3ECC> <@W4R5LUPK3> <@U0213T59LMN> (edited)',
    user: 'W4R4S9FS4',
    team: 'T06DUTYDQ',
    client_msg_id: 'ff0ded2c-4a11-42fa-b0e4-0e690337741b'
  },
  {
    ts: '1747994400.611139',
    text: ':customervivo:*Customer Name : NFCU*\n:clock2: *Date :* 2025-05-22\n:group-people: *Attendees :* <@W010NNJV7S8>\n:loading-2248:*Notes*\n• NFCU talked about expanding the adoption of IC Editor internally, subject to maturity of the product.\n• They have 2 projects coming up spanning across other departments in NFCU in the next quarter, that would start in mid June\n• The major requirement of the 1st project data binding from APIs\n• The requirements for the 2nd project is still being figured out, but based on the rudimentary details they currently have, it seems to make a good fit for Associate UI\n:todo_done: *Next Action*\n• NFCU will come back with more refined requirements in the next call\n• They are interested in seeing the current status of the IC Editor, and update it in their dev and stage environments\n• Adobe to showcase current status and share high level Roadmap\n',
    user: 'W4R4S9FS4',
    team: 'T06DUTYDQ',
    client_msg_id: 'ba23958e-38ad-43d5-b57c-b387a029e256'
  },
  {
    ts: '1747914861.490979',
    text: 'Reminder: *Please send following updates in threaded view on slack*\n*1. Updates since the last sync up.*\n*2. Are you blocked on anything?*\n*3. What is the next milestone to be achieved.*',
    user: 'W4R4S9FS4',
    team: 'T06DUTYDQ',
    client_msg_id: 'fea00f0a-b8cd-4fbd-bb61-cbb6c0f4c444'
  },
  {
    ts: '1747914835.578449',
    text: ':customervivo:*Customer Name : IRS*\n:clock2: *Date :* 2025-05-20\n:group-people: *Attendees :* <@W4XTCQ07J>, <@U0213T59LMN>, <@W4RU5J3JR>, <@W4R4S9FS4>, <@W5HEU5M7Y>, <@W4R5LUPK3>\n:loading-2248:*Notes*\nGenerated by AI.\n*IRS attendees* (_there were more attendees from IRS - but active participants were_):\n• JP Terry\n• Ande Vara Prasada Rao\n• Gower Andrew R\n*Meeting notes:*\n• *Automated Forms Conversion Service Demo:*\n• \n    ◦ *Automated Forms Conversion Service Configuration:* Gaurav demonstrated the configuration of the automated forms conversion service on a local setup, including adding developers, creating projects, and configuring the service on the AM instance.\n        ▪︎ *Service Configuration:* Gaurav explained that when the Automated Forms Conversion (AFC) service is provisioned for an organization, an administrator is assigned to add developers responsible for configuring the service on the AM instance. The administrator uses the admin console to add developers to the product profile.\n        ▪︎ *Developer Console:* After being added, developers need to create a project in the developer console, add an API, and configure server-to-server authentication. Gaurav demonstrated creating a new project and selecting the automated forms conversion API.\n        ▪︎ *Client ID and Secret:* Gaurav showed that after configuring the API, developers receive a client ID, client secret, scopes, and organization ID. These details are used to configure the AM local server by going to the security settings and Adobe IMS configurations.\n        ▪︎ *Health Check:* Gaurav performed a health check to ensure the configuration was correct, confirming successful token retrieval and authentication for the automated forms conversion service.\n    ◦ *Cloud Configuration for Automated Forms Conversion:* Gaurav explained the process of creating a cloud configuration for the automated forms conversion service, including selecting templates and themes for the converted forms.\n        ▪︎ *Cloud Services:* Gaurav navigated to the cloud services section to create a cloud configuration for the automated forms conversion service. He demonstrated selecting a contribution folder and naming the configuration.\n        ▪︎ *Endpoint and Template:* Gaurav explained that the endpoint for accessing the service and the template type (foundation-based or core component-based) are selected during the configuration. He showed how to choose a template and a theme for the converted form.\n        ▪︎ *Configuration Example:* Gaurav provided examples of configurations for both V2 (core component-based) and foundation-based templates, showing the IMS and cloud configurations already set up.\n    ◦ *Conversion of PDF to Adaptive Forms:* Gaurav showed how to upload a PDF and start the automated conversion process, resulting in an adaptive form with the same fields and structure as the original PDF.\n        ▪︎ *PDF Upload:* Gaurav demonstrated uploading a PDF document with fields such as date, reason, total amount, and text areas. He explained that the document is uploaded to the AM instance.\n        ▪︎ *Start Conversion:* Gaurav showed how to select the uploaded PDF, choose the desired configuration (V1 or V2), and start the automated conversion process. The configurations are prefilled with the selected template and theme, but can be overridden if needed.\n        ▪︎ *Conversion Process:* Gaurav explained that the conversion process involves sending a request to the AI/ML service, which processes the images and creates an adaptive form. He showed the converted output, highlighting that the fields and structure matched the original PDF.\n        ▪︎ *Foundation and Core Components:* Gaurav demonstrated the converted outputs for both foundation-based and core component-based forms, showing that the fields were correctly identified and configured in the adaptive forms.\n    ◦ *AI and Machine Learning in Forms Conversion:* Ande and Gaurav discussed the role of AI and machine learning in identifying widgets and fields in the PDF during the conversion process.\n        ▪︎ *AI Role:* Gaurav explained that AI helps identify widgets and fields in the PDF, such as captions and input fields, by analyzing the structure of the form. The AI models group related captions and fields to create adaptive form fields.\n        ▪︎ *Field Grouping:* Gaurav provided an example where the AI grouped a caption and input field to create a field for capturing the insured name. He also explained how sections and panels are identified and extracted from the PDF.\n        ▪︎ *Vision Models:* Gaurav mentioned that vision models and machine learning models are used to identify the structure, fields, sections, and captions in the PDF, enabling the creation of adaptive forms from straightforward PDF screenshots.\n    ◦ *Issues with Core Component Template:* Terry raised an issue with the core component template failing to convert forms, and Gaurav suggested providing the latest build and enabling a feature toggle to resolve the issue.\n        ▪︎ *Issue Raised:* Terry reported that while the foundation component template worked fine, the core component template failed to convert forms, displaying an error message suggesting retrying the conversion or contacting Adobe support.\n        ▪︎ *Latest Build:* Gaurav acknowledged the issue and suggested that the latest build and enabling a feature toggle could resolve the problem. He mentioned that the core component form conversion support was recently added.\n        ▪︎ *Configuration Steps:* Terry asked if any additional steps were needed on the server. Gaurav confirmed that once the latest code and feature toggle are enabled, creating a new configuration with the core component template should work.\n        ▪︎ *Service Pack:* Terry inquired about the required service pack version. Gaurav promised to confirm whether a new service pack or the existing one (6.5.22 or 6.5.23) would suffice and share the necessary details.\n    ◦ *Custom Components and Meta Model:* Gaurav explained how to use the meta model to map custom components to specific fields during the forms conversion process.\n        ▪︎ *Meta Model:* Gaurav introduced the concept of the meta model, which allows extending out-of-the-box configurations by mapping custom components to specific fields identified in the PDF during the conversion process.\n        ▪︎ *Custom Component Mapping:* Gaurav demonstrated how to map a custom component, such as an SSN field, by providing a mapping in a JSON file. This mapping ensures that the custom component is used instead of the default component during conversion.\n        ▪︎ *Configuration Path:* Gaurav showed that the custom meta model can be uploaded to the AM instance, and the path to the JSON file can be specified in the cloud configuration to apply the custom mappings during conversion.\n        ▪︎ *Form Level Validations:* Ande asked about including form-level validations in the meta model. Gaurav confirmed that properties such as required fields, default values, and validation rules can be added to the JSON file and applied during conversion.\n    ◦ *Security Concerns with Cloud-Based Conversion:* Ande asked about security concerns with cloud-based conversion, and Anurag assured that the communication is secure and within the IRS authenticated context.\n    ◦ *Popularity of Automated Forms Conversion Service:* Ande inquired about the popularity of the service, and Anurag confirmed that several customers have been using it since its release in 2017-2018.\n• *Generative AI Demo:* Gaurav demonstrated the capabilities of the Form Experience Builder, a conversational assistant that helps in authoring and creating form experiences using generative AI.\n    ◦ *Form Creation:* Gaurav demonstrated the Form Experience Builder, which uses generative AI to create forms based on user-provided intents. He showed how to enter an intent, select a template and theme, and create a form.\n    ◦ *Assistant Interface:* Gaurav explained the assistant interface, which provides commands for creating and updating forms. He demonstrated adding a panel, updating the layout, and creating business logic using the assistant.\n    ◦ *Rule Creation:* Gaurav showed how to create a rule for setting an email address based on the first and last names. The assistant generated the rule, and Gaurav confirmed its functionality in the preview mode.\n• *Cloud Sandbox for Generative AI:* Arun suggested setting up a cloud sandbox for the IRS team to use the generative AI technology for creating forms, as it is currently only available in the cloud version.\n:todo_done: *Next Action*\n• *Next Steps for Core Component Support:* Arun and Terry discussed the next steps for enabling core component support in the automated forms conversion service, including backporting changes and providing a hotfix.\n• *Impact on Form Digitization Plans:* Arun and Terry discussed how the new features and tools could expedite the digitization and modernization of IRS forms, with a focus on enabling core component support first.\nFollow-up tasks:\n\n    ◦ *Core Component Conversion Issue:* Confirm whether the latest code or service pack is required for core component conversion and share the necessary details with Terry. (Gaurav)\n    ◦ *Core Component Conversion Issue:* Provide Terry with the latest build or hotfix for core component conversion and enable the feature toggle. (Anurag)\n    ◦ *Core Component Conversion Issue:* Set up a new server dedicated to testing the core component conversion and ensure it is configured correctly. (Terry)\n    ◦ *Core Component Conversion Issue:* Submit a support ticket to enable the feature toggle for core component conversion on the IRS account. (Ande)\n    ◦ *Core Component Conversion Issue:* Discuss internally and provide an ETA for the hotfix and feature toggle for core component conversion. (Anurag)\n    ◦ *Core Component Conversion Issue:* Run a test on the core component conversion and report any additional requirements or issues. (Terry)\n    ◦ *Cloud Sandbox Setup:* Discuss and set up a cloud sandbox for testing the generative AI and other advanced features. (Arun)\n    ◦ *Form Conversion Sections:* Share the PDF form with Gaurav to review and ensure it converts into sections correctly. (None) - <https://www.irs.gov/pub/irs-pdf/f433aoi.pdf>\n',
    user: 'W4R4S9FS4',
    team: 'T06DUTYDQ',
    client_msg_id: '277b5ad5-64c9-46a3-bc2d-ef574c0f0926'
  },
  {
    ts: '1747906072.251329',
    text: ':customervivo:*Customer Name : LPL Financial*\n:clock2: *Date :* 2025-05-21\n:group-people: *Attendees :* <@W9QMZFR39>, <@W4R4VBWQG>, <@U0213T59LMN>, <@W4RU708G5>, <@W4RU5J3JR>, <@W4RRL6DDY>\n:loading-2248:*Notes*\n• Presented two major use cases for form pre-filling(from user entered data and from incoming persisted Json) and the current approach involving manual conversion and data binding, highlighting scalability issues. We got confirmation from the customer about pain points and workflow.\n• They discussed the challenges of converting forms from Word documents to AEM forms, emphasizing the time-consuming nature of the process. They also mentioned that incoming Form can be in word format also.\n• Demonstrated AFCS with its current capabilities and how these can be leveraged to address certain use cases in the existing implementation. Specifically, we showcased the flow: Acroform PDF → AF → Auto DoR.\n• Demonstrated the Forms Experience Builder, showcasing its ability to create and modify forms using natural language input and images.\n• We also demonstrated a PoC where Forms Experience Builder analyzes AFCS-converted Adaptive Forms for quality issues, aiming to enhance the accuracy of automated conversions. This is in Dev and we are working on it for improving its quality.\n:todo_done: *Next Action*\n• *AI Feature Access:* Check with the relevant team and enable AI feature access on LPL\'s sandbox account. (Adobe)\n• *Weekly Sync Setup:* Sync up with Naveen offline to set up weekly sessions starting next week. (Adobe)\n• *Priority Forms:* Share priority forms with Adobe for conversion and analysis. (LPL)\n• *Recording of Meeting:* Send the recording of today\'s meeting to Tian. (Adobe)\n',
    user: 'W4R4S9FS4',
    team: 'T06DUTYDQ',
    client_msg_id: '350fe454-9661-4b43-b059-36e1d0128375'
  }
];

const CHANNEL_ID = 'C08T43UHK9D';
const CHANNEL_NAME = 'anusharm-test-channel';

async function ingestMessages() {
  console.log('\n📥 Ingesting messages from Slack channel');
  console.log('==========================================');
  console.log(`   Channel ID: ${CHANNEL_ID}`);
  console.log(`   Channel Name: ${CHANNEL_NAME}`);
  console.log(`   Messages to ingest: ${messages.length}\n`);
  
  let ingestedCount = 0;
  let errorCount = 0;
  
  for (const message of messages) {
    try {
      const signal: RawSignal = {
        source: 'slack',
        id: message.ts,
        type: 'message',
        text: message.text,
        metadata: {
          channel_id: CHANNEL_ID,
          channel_name: CHANNEL_NAME,
          user: message.user,
          timestamp: message.ts,
          team: message.team,
          client_msg_id: message.client_msg_id
        }
      };
      
      const result = await ingestSignal(signal);
      ingestedCount++;
      console.log(`✅ Ingested message ${message.ts.substring(0, 10)}... (${ingestedCount}/${messages.length})`);
      logger.debug('Message ingested', { 
        signalId: result.id,
        messageId: message.ts,
        userId: message.user
      });
    } catch (error: any) {
      errorCount++;
      console.error(`❌ Failed to ingest message ${message.ts}:`, error.message);
      logger.error('Failed to ingest message', { 
        error: error.message,
        messageId: message.ts,
        stack: error.stack
      });
    }
  }
  
  console.log('\n📊 Ingestion Summary:');
  console.log(`   Total messages: ${messages.length}`);
  console.log(`   Successfully ingested: ${ingestedCount}`);
  console.log(`   Errors: ${errorCount}\n`);
  
  return { ingestedCount, errorCount, total: messages.length };
}

if (require.main === module) {
  ingestMessages()
    .then(result => {
      if (result.errorCount === 0) {
        console.log('✅ All messages ingested successfully!\n');
        process.exit(0);
      } else {
        console.log(`⚠️  Completed with ${result.errorCount} errors\n`);
        process.exit(1);
      }
    })
    .catch(error => {
      console.error('\n❌ Fatal error:', error.message);
      logger.error('Fatal error in ingestion script', { error: error.message, stack: error.stack });
      process.exit(1);
    });
}

export { ingestMessages };
