/**
 * End-to-end API test for PM Intelligence System.
 * Covers: health, ingest, detect, list opportunities, signals-by-opportunity,
 * create judgment, create artifact, list artifacts, metrics.
 */

import * as dotenv from 'dotenv';
dotenv.config();

const API_BASE = process.env.API_BASE || 'http://localhost:3000';

async function jsonFetch(url: string, options?: RequestInit) {
  const res = await fetch(url, options);
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} ${res.statusText}: ${text}`);
  }
  return text ? JSON.parse(text) : {};
}

async function main() {
  console.log('== PM Intelligence API E2E Test ==');
  console.log(`API_BASE: ${API_BASE}\n`);

  console.log('1) Health check');
  const health = await jsonFetch(`${API_BASE}/health`);
  console.log(`   status=${health.status} db_connected=${health.database?.connected}\n`);

  console.log('2) Ingest test signals');
  const ingestPayloads = [
    { source: 'test', text: 'Test signal: user unable to export report', type: 'bug_report' },
    { source: 'test', text: 'Test signal: customer wants scheduled exports', type: 'feature_request' },
    { source: 'test', text: 'Test signal: export failed with timeout errors', type: 'bug_report' }
  ];
  const ingested = [];
  for (const payload of ingestPayloads) {
    const signal = await jsonFetch(`${API_BASE}/api/signals`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
    ingested.push(signal.id);
  }
  console.log(`   ingested=${ingested.length}\n`);

  console.log('3) Detect opportunities (incremental)');
  const detect = await jsonFetch(`${API_BASE}/api/opportunities/detect/incremental`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' }
  });
  console.log(`   detected=${Array.isArray(detect) ? detect.length : 0}\n`);

  console.log('4) List opportunities');
  const oppsResp = await jsonFetch(`${API_BASE}/api/opportunities?limit=10`);
  const opportunities = oppsResp.opportunities || [];
  if (opportunities.length === 0) {
    throw new Error('No opportunities found after detection.');
  }
  const opportunity = opportunities[0];
  console.log(`   selected=${opportunity.title || opportunity.id}\n`);

  console.log('5) Get signals for opportunity');
  const signals = await jsonFetch(`${API_BASE}/api/opportunities/${opportunity.id}/signals`);
  console.log(`   signals_count=${Array.isArray(signals) ? signals.length : 0}\n`);

  console.log('6) Create judgment');
  const judgmentPayload = {
    opportunityId: opportunity.id,
    userId: 'test-user@example.com',
    analysis: 'Test analysis for opportunity from API E2E test.',
    recommendation: 'Investigate further and validate with customers.',
    confidence: 0.7,
    reasoning: 'Generated by automated E2E test.'
  };
  const judgment = await jsonFetch(`${API_BASE}/api/judgments`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(judgmentPayload)
  });
  console.log(`   judgment_id=${judgment.id} confidence_level=${judgment.confidence_level}\n`);

  console.log('7) Create artifact');
  const artifactPayload = {
    judgmentId: judgment.id,
    type: 'PRD',
    content: `# PRD (Test)\n\nThis is a test artifact for ${opportunity.title || opportunity.id}.`
  };
  const artifact = await jsonFetch(`${API_BASE}/api/artifacts`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(artifactPayload)
  });
  console.log(`   artifact_id=${artifact.id} type=${artifact.artifact_type}\n`);

  console.log('8) List artifacts for judgment');
  const artifacts = await jsonFetch(`${API_BASE}/api/artifacts/${judgment.id}`);
  console.log(`   artifacts_count=${Array.isArray(artifacts) ? artifacts.length : 0}\n`);

  console.log('9) Metrics');
  const metrics = await jsonFetch(`${API_BASE}/api/metrics`);
  console.log(`   totals: signals=${metrics.total_signals} opps=${metrics.total_opportunities} judgments=${metrics.total_judgments} artifacts=${metrics.total_artifacts}\n`);

  console.log('== E2E API Test Complete ==');
}

main().catch((error) => {
  console.error('E2E API test failed:', error.message || error);
  process.exit(1);
});
